### ISSUE TITLE
快捷键亮度调节不可用

### ISSUE THREAD

**Issue by LeanFly** [WentaoHao/LenovoHackIntoSh-IdeaPad310s14Ikb#1]
同IdeaPad310s-14-ikb，8G内存
使用键盘上的亮度调节快捷键不起作用，音量调节的快捷键正常。
原本的10.15.3亮度调节不可用，升级到了10.15.5仍然不可用。
能否告知亮度调节修复的解决方案

**Comment by WentaoHao** [comment]
我应该只是使用了AppleBacklightFixup.kext 和 SSDT-PNLF.aml,这两个文件以及用法可以从下面的链接获得:
https://github.com/RehabMan/AppleBacklightFixup

**Comment by LeanFly** [comment]
> 我应该只是使用了AppleBacklightFixup.kext 和 SSDT-PNLF.aml,这两个文件以及用法可以从下面的链接获得:
> https://github.com/RehabMan/AppleBacklightFixup

好的好的，我试试，多谢大佬指点
